In [1]:
import numpy as np

In [2]:
X = np.array([1, 1.4, 2.5]) ## first value must be 1
w = np.array([0.4, 0.3, 0.5])

In [3]:
def net_input(X, w):
    return np.dot(X, w)

In [4]:
def logistic(z):
    return 1.0 / (1.0 + np.exp(-z))

In [5]:
def logistic_activation(X, w):
    z = net_input(X, w)
    return logistic(z)

In [6]:
print('P(y=1|x) = %.3f' % logistic_activation(X, w))

P(y=1|x) = 0.888


In [7]:
W = np.array([[1.1, 1.2, 0.8, 0.4], [0.2, 0.4, 1.0, 0.2], [0.6, 1.5, 1.2, 0.7]])
A = np.array([[1, 0.1, 0.4, 0.6]])
Z = np.dot(W, A[0])
y_probas = logistic(Z)
print('Net Input: \n', Z)
print('Output Units:\n', y_probas)

Net Input: 
 [1.78 0.76 1.65]
Output Units:
 [0.85569687 0.68135373 0.83889105]


In [8]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z))

In [9]:
y_probas = softmax(Z)

In [10]:
print('Probabilities:\n', y_probas)

Probabilities:
 [0.44668973 0.16107406 0.39223621]


In [11]:
np.sum(y_probas)

1.0